# Utilisez l'image "imageA" comme première étape de construction
FROM alpine:latest AS imageA

# Installation des dépendances pour la génération de certificats
RUN apk update && apk add --no-cache ca-certificates openssl

# Créez le répertoire pour stocker les certificats
RUN mkdir /certs

# Définissez le répertoire de travail
WORKDIR /certs

# Copiez le script de génération de certificats dans le conteneur
COPY generate_certs.sh .

# Rendez le script exécutable
RUN chmod 711 generate_certs.sh

# Définissez l'entrée principale du conteneur
RUN ./generate_certs.sh

# Utilisez l'image "nginx" comme deuxième étape de construction
FROM nginx:latest

# Copiez le fichier de configuration NGINX
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=imageA /certs/localhost.crt /etc/nginx/localhost.crt
COPY --from=imageA /certs/localhost.key /etc/nginx/localhost.key

# Définissez les ports exposés
EXPOSE 80
