FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt /app/
COPY .env /app/
COPY app.py /app/
COPY .gitignore /app/

RUN apt-get update \
&& pip install --upgrade pip \
&& pip install -r requirements.txt


EXPOSE 5000

# -m flask run --host=172.18.0.6
CMD ["python3", "app.py"]


