# Utilisez l'image Nginx officielle
FROM nginx:latest

# Supprimez le fichier de configuration par défaut de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiez votre configuration Nginx personnalisée dans le conteneur
COPY nginx-config/nginx.conf /etc/nginx/conf.d/nginx.conf

# Copiez les certificats SSL dans le conteneur (si nécessaire)
COPY ssl-certs/ /etc/nginx/ssl-certs/

# Exposez les ports HTTP et HTTPS (80 et 443)
EXPOSE 80
EXPOSE 88
EXPOSE 443

# Commande pour exécuter Nginx en mode daemon
CMD ["nginx", "-g", "daemon off;"]

