global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']  # Remplacer 'jaeger' par le nom du service Jaeger si nécessaire

  - job_name: 'netdata'
    static_configs:
      - targets: ['netdata:19999']  # Remplacer 'netdata' par le nom du service Netdata si nécessaire